name:  Gemini AI Docs Updater

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'

permissions:
  contents: write
  id-token: write

jobs:
  update_documentation:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'docs:')"

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 2. Get Changed Files
        id: changed_files
        run: |
          echo "files=$(git diff --name-only HEAD~1 HEAD | grep -vE '^(docs/|README.md|\.github/)' | xargs)" >> $GITHUB_OUTPUT

      - name: 3. Run Gemini Docs Generator
        if: steps.changed_files.outputs.files != ''
        id: gemini_run
        uses: google-gemini/gemini-cli-action@main
        with:
          # ⚠️ Erstatt med dine Google Cloud-verdier
          project_id: 'YOUR_PROJECT_ID'
          service_account: 'your-service-account@your-project-id.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/YOUR_PROJECT_ID/locations/global/workloadIdentityPools/YOUR_POOL_ID/providers/YOUR_PROVIDER_ID'
          # Kommandoen som skal kjøres
          command: bash .github/scripts/generate_docs.sh "${{ steps.changed_files.outputs.files }}" > temp_docs.md

      - name: 4. Commit and Push Documentation
        if: steps.gemini_run.outcome == 'success'
        run: |
          mv temp_docs.md docs/overview.md
          
          git config --global user.name 'Gemini Doc Bot'
          git config --global user.email 'gemini-bot@users.noreply.github.com'
          git add docs/overview.md
          
          if ! git diff --staged --quiet; then
            git commit -m "docs: ✨ automatic update by Gemini"
            git push
          else
            echo "No documentation changes were generated."
          fi
